// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements CancelOrder operation.
	//
	// Отменяет заказ.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateNewOrder implements CreateNewOrder operation.
	//
	// Создаёт новый заказ на основе выбранных
	// пользователем деталей.
	//
	// POST /api/v1/orders
	CreateNewOrder(ctx context.Context, req *CreateOrderRequest) (CreateNewOrderRes, error)
	// GetOrderByUuid implements GetOrderByUuid operation.
	//
	// Возвращает информацию о заказе.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderByUuid(ctx context.Context, params GetOrderByUuidParams) (GetOrderByUuidRes, error)
	// OrderPay implements OrderPay operation.
	//
	// Проводит оплату ранее созданного заказа.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	OrderPay(ctx context.Context, req *PayOrderRequest, params OrderPayParams) (OrderPayRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
