// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements CancelOrder operation.
//
// Отменяет заказ.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r CancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateNewOrder implements CreateNewOrder operation.
//
// Создаёт новый заказ на основе выбранных
// пользователем деталей.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateNewOrder(ctx context.Context, req *CreateOrderRequest) (r CreateNewOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderByUuid implements GetOrderByUuid operation.
//
// Возвращает информацию о заказе.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderByUuid(ctx context.Context, params GetOrderByUuidParams) (r GetOrderByUuidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderPay implements OrderPay operation.
//
// Проводит оплату ранее созданного заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) OrderPay(ctx context.Context, req *PayOrderRequest, params OrderPayParams) (r OrderPayRes, _ error) {
	return r, ht.ErrNotImplemented
}
