// Code generated by ogen, DO NOT EDIT.
package order_v1

type CancelOrderRes interface {
	cancelOrderRes()
}

type CreateNewOrderRes interface {
	createNewOrderRes()
}

type GetOrderByUuidRes interface {
	getOrderByUuidRes()
}

type OrderPayRes interface {
	orderPayRes()
}
