// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOrderOperation    OperationName = "CancelOrder"
	CreateNewOrderOperation OperationName = "CreateNewOrder"
	GetOrderByUuidOperation OperationName = "GetOrderByUuid"
	OrderPayOperation       OperationName = "OrderPay"
)
