// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ianagovitsyn/project/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) CancelOrder(ctx context.Context, orderUUID string) error {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *OrderService_Expecter) CancelOrder(ctx interface{}, orderUUID interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, orderUUID)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, orderUUID string)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(_a0 error) *OrderService_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(context.Context, string) error) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNewOrder provides a mock function with given fields: ctx, params
func (_m *OrderService) CreateNewOrder(ctx context.Context, params model.CreateOrderParams) (model.Order, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderParams) (model.Order, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateOrderParams) model.Order); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateOrderParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CreateNewOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewOrder'
type OrderService_CreateNewOrder_Call struct {
	*mock.Call
}

// CreateNewOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - params model.CreateOrderParams
func (_e *OrderService_Expecter) CreateNewOrder(ctx interface{}, params interface{}) *OrderService_CreateNewOrder_Call {
	return &OrderService_CreateNewOrder_Call{Call: _e.mock.On("CreateNewOrder", ctx, params)}
}

func (_c *OrderService_CreateNewOrder_Call) Run(run func(ctx context.Context, params model.CreateOrderParams)) *OrderService_CreateNewOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateOrderParams))
	})
	return _c
}

func (_c *OrderService_CreateNewOrder_Call) Return(_a0 model.Order, _a1 error) *OrderService_CreateNewOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CreateNewOrder_Call) RunAndReturn(run func(context.Context, model.CreateOrderParams) (model.Order, error)) *OrderService_CreateNewOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function with given fields: ctx, OrderUUID
func (_m *OrderService) GetByUUID(ctx context.Context, OrderUUID string) (model.Order, error) {
	ret := _m.Called(ctx, OrderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, OrderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, OrderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, OrderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type OrderService_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - OrderUUID string
func (_e *OrderService_Expecter) GetByUUID(ctx interface{}, OrderUUID interface{}) *OrderService_GetByUUID_Call {
	return &OrderService_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, OrderUUID)}
}

func (_c *OrderService_GetByUUID_Call) Run(run func(ctx context.Context, OrderUUID string)) *OrderService_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_GetByUUID_Call) Return(_a0 model.Order, _a1 error) *OrderService_GetByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetByUUID_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *OrderService_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// OrderPay provides a mock function with given fields: ctx, paymentMethod, OrderUUID
func (_m *OrderService) OrderPay(ctx context.Context, paymentMethod model.PaymentMethod, OrderUUID string) (string, error) {
	ret := _m.Called(ctx, paymentMethod, OrderUUID)

	if len(ret) == 0 {
		panic("no return value specified for OrderPay")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PaymentMethod, string) (string, error)); ok {
		return rf(ctx, paymentMethod, OrderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PaymentMethod, string) string); ok {
		r0 = rf(ctx, paymentMethod, OrderUUID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PaymentMethod, string) error); ok {
		r1 = rf(ctx, paymentMethod, OrderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_OrderPay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderPay'
type OrderService_OrderPay_Call struct {
	*mock.Call
}

// OrderPay is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentMethod model.PaymentMethod
//   - OrderUUID string
func (_e *OrderService_Expecter) OrderPay(ctx interface{}, paymentMethod interface{}, OrderUUID interface{}) *OrderService_OrderPay_Call {
	return &OrderService_OrderPay_Call{Call: _e.mock.On("OrderPay", ctx, paymentMethod, OrderUUID)}
}

func (_c *OrderService_OrderPay_Call) Run(run func(ctx context.Context, paymentMethod model.PaymentMethod, OrderUUID string)) *OrderService_OrderPay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PaymentMethod), args[2].(string))
	})
	return _c
}

func (_c *OrderService_OrderPay_Call) Return(_a0 string, _a1 error) *OrderService_OrderPay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_OrderPay_Call) RunAndReturn(run func(context.Context, model.PaymentMethod, string) (string, error)) *OrderService_OrderPay_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
